NBK: Reorg VDP to simplify
1. Put experiment parameters up front
2. Remove/combine a bunch of unneccessary cells

It appears the model works well with t1=100, 50 measurement times,
.1 noise (~7.8%) and no annealing.  Decreasing the amount of data
can work for a bit if annealing is enabled, but broadly, if there is
less data, data weight needs to come increase.

interested:
t1=100, nt=50
(x)'' = -0.987 x + 0.363 (x') + -0.361 x^2 (x')
t1=100, nt=25
In Annealing...Optimizer
TypeError: sub got incompatible shapes for broadcasting: (1000,), (0,).
t1=75, nt=50, annealing=True
(x)'' = -0.969 x